[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bcrypt = "0.15.1"
regex = "1.11.0"
sea-orm = { version = "1.0.1" }
serde = { version = "1.0.210", features = ["derive"] }
slug = "0.1.6"
